#!/bin/bash

if ! which ampy >/dev/null; then
    echo "ampy isn't installed. Please install it and try again." 
    exit 1
fi

if { ampy -p /dev/ttyACM0 ls 2>&1 >&3 3>&- | grep '^' >&2; } > /dev/null 2>&1 3>&1; then 
    echo "Could not talk to the interstate75 board on /dev/ttyACM0"
    exit 2
fi

echo "Removing existing content"

