from graphics.colours import RGBColour

_SPACE_INVADER_RED = RGBColour(0xF83B3A)
_SPACE_INVADER_YELLOW = RGBColour(0xEBDF64)
_SPACE_INVADER_GREEN = RGBColour(0x62DE6D)
_SPACE_INVADER_MAGENTA = RGBColour(0xDB55DD)
_SPACE_INVADER_INDIGO = RGBColour(0x5353F1)
_SPACE_INVADER_CYAN = RGBColour(0x42E9F4)

